### PR TITLE
Change delivery steps

### PR DESCRIPTION
**Pull request by kandalf**
This PR proposes a change for the delivery steps the candidates should take.

The proposed changes simplify the workflow for candidates and keep the original repository free from junk code and branches.

Please take a look and let me know what you think. Also (specially @seldomatt) advise on the wording, please.

### CODE REVIEW

**Review by damianfarina — APPROVED** [review]
Agreed 💯 
I just went through the instructions and it's way too confusing.

**Comment by rodrei** [comment]
👍 I'd like to merge this, but I don't have permissions. I'll try to get it merged.

**Comment by kandalf** [comment]
@rodrei Merged!

**Comment by rodrei** [comment]
Beautiful!

**Pull request merged**
